### ISSUE TITLE
Not working with hidden thrusters

### ISSUE THREAD

**Issue by thghca** [1wsx10/VectorThrust2#3]

**Comment by 1wsx10** [comment]
what do you mean? can you give me an example?

**Comment by thghca** [comment]
If i hide thruster from terminal rotors react inputs but thruster orients orthogonally and not powered.

**Comment by 1wsx10** [comment]
this is a feature. you can use it to tell the script to not use specific thrusters.

unfortunately, keen doesn't allow scripts to add buttons or sliders to terminal blocks (i can dream). instead you have to use custom data which is unfriendly to the user, and you can't change it with timers or buttons, so i don't want to use it.

this is the most inconsequential toggle imo so thats what im using to tell the script not to use certain thrusters.

you can turn the thruster off if the script is on, but that resets when you recompile and can't be done if the script has turned the thruster off (no force required, it avoids dampeners... again, thanks keen) or is in standby.
