### ISSUE TITLE
When landed and gears locked some nacelles sometimes shakes very fast. 

### ISSUE THREAD

**Issue by thghca** [1wsx10/VectorThrust2#4]
It tries to compensate insignificant microwobbling of grid and sets maximum rotation speed on rotor, overshoot and start again.
https://youtu.be/aTdQL1b4Atc

**Comment by 1wsx10** [comment]
what are your settings?

**Comment by 1wsx10** [comment]
this should be fixed from a few updates ago.
when you have landing gear on a static grid, the mass reads as 0. this means force from gravity is also 0... so, without any user input, the rotors didn't know which direction to point. this was also an issue in space.

currently, if the force required is below a certain threshold, the rotor goes to a home position. its not a perfect solution, but its better than nothing.

perhaps a better solution is varying the rotor torque depending on how much force is required from the nacelles. but that might be an issue with the KFT.
