### ISSUE TITLE
 Missing ability to set state 

### ISSUE THREAD

**Issue by ETHREAL1** [1wsx10/VectorThrust2#9]
While making some ships and drones I’ve discovered an issue, that issue is for safety reasons I have the scrip set to start with standby off for things like server crashes or local games crashing, but then if you use a scrip like isys auto refueler or auto docking scrips that can trigger a timer block that in theory would trigger standby on Vector Thrust, the problem that appears is after a game restart or server reboot if the ship is docked because there is only a toggle standby not set standby the state of standby can easily become inverted as in thrusters on when docked then switched off when undocking.

If two commands could be added namely %standbyon and %standbyoff with a simple bool check to see what state it currently is in then toggle if needed to make it the desired state, that’s all that’s needed.

**Comment by 1wsx10** [comment]
please make a pull request if you want features added
